name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Create release PR or GitHub release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89f4291f2343dd4e3e154 # v4.2.0
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: Publish to npm
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20
    environment: main_branch
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setting up Node.js
        uses: ./.github/actions/setup-node

      - name: Installing dependencies
        run: pnpm i

      - name: Build package
        run: pnpm run build:publish

      - name: Publishing to npm
        # pnpm doesn't work - refs: https://github.com/pnpm/pnpm/issues/4937
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
